version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./backend:/app 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/ssl 
    ports:
      - "443:443"  
      - "80:80"  
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data: {}